version: '3.8'

services:
  db:
    container_name: "db"
    image: mysql:latest
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hello-me
      MYSQL_DATABASE: levi

    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name:  "levi"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - db
    depends_on:
      - db
    volumes: 
      - .:/app
      - '/app/node_modules'

networks:
  default:
volumes:
  mysql_data: